package io.casehub.drafthouse.debate;

public enum EntryType {
    RAISE, AGREE, COUNTER, DISPUTE, QUALIFY, FLAG_HUMAN, DECLINED,
    VERIFIED, DEFERRED,
    MEMO,
    SUB_TASK_REQUEST,
    SUB_TASK_FINDING,
    SUB_TASK_ERROR,
    RESTART_CONTEXT,
    ROUND_SNAPSHOT,
    COMMENT,
    HUMAN_OVERRIDE,
    REPRIORITISE
}
